### ISSUE TITLE
0.6.1 introduces new warning with ClojureScript

### ISSUE THREAD

**Issue by jeaye** [metosin/spec-tools#108]
After upgrading from `0.5.1` to `0.6.1`, I see this warning whenever I compile with ClojureScript (`1.9.946`).

```text
WARNING: Use of undeclared Var spec-tools.impl/resolve-form at line 365 target/android/spec_tools/core.cljc
```

I haven't noticed any issues caused by it, but it wasn't there before!

**Comment by miikka** [comment]
Thanks for the report! The warning comes from code that was introduced in version 0.6.0 (PR #91 and some further work). There are tests for that code, so I *suppose* it works. It looks like the compiler is complaining about macro code using a var that's not supposed to be seen by the ClojureScript side in the first place (unless you use self-hosted Cljs, but we don't support that yet anyway).

Still, spec-tools shouldn't cause compiler warnings. I poked the code at bit, but couldn't immediately figure it out. If you or somebody else wants to contribute a patch, go ahead.
