### ISSUE TITLE
coll? maps to double in json schema transform

### ISSUE THREAD

**Issue by solussd** [metosin/spec-tools#113]
https://github.com/metosin/spec-tools/blob/c9053c935bd91afe1b3e93cd727e0896d039b190/src/spec_tools/json_schema.cljc#L155

This method is then redefined in the next form, so it's not really a bug, per se, at runtime.

**Comment by ikitommi** [comment]
Looks like it should be `rational?` (https://github.com/metosin/spec-tools/blob/c9053c935bd91afe1b3e93cd727e0896d039b190/src/spec_tools/json_schema.cljc#L154-L155)

**Comment by solussd** [comment]
I think that's right.
