### ISSUE TITLE
Conforming through or / multi-spec?

### ISSUE THREAD

**Issue by rgould1** [metosin/spec-tools#114]
I've just found the library, so apologies if I'm missing something obvious, but I'd really like to be able to use the functionality of strip-extra-keys-conforming, but where my spec is branched in some way. For example

```(spec/def ::a integer?)
(spec/def ::b string?) 
(spec/def ::map (spec/keys :req [::a ::b]))
(spec/def ::or (spec/or :1 ::map :2 string?))
(st/conform  (st/spec ::or)  {::a 1   ::b "abc"   ::c :hello}  st/strip-extra-keys-conforming)
=> [:1 {:a 1, :b "abc", :c :hello}] ;; keyword :c remains

**Comment by ikitommi** [comment]
hi. `clojure.spec` doesn't support natively selective runtime transformations so and to support that, one needs to wrap all spec into `spec-tools.core/spec`, so you need to:

```clj
(require '[clojure.spec.alpha :as s])
(require '[spec-tools.core :as st])

(s/def ::b string?)
(s/def ::map (st/spec (s/keys :req [::a ::b])))
(s/def ::or (s/or :1 ::map :2 string?))
(st/conform (st/spec ::or) {::a 1 ::b "abc" ::c :hello} st/strip-extra-keys-conforming)
;; [:1 #:user{:b "abc", :a 1}]
```

See Cognitect answers on removing the need to wrap:
* https://dev.clojure.org/jira/browse/CLJ-2116
* https://dev.clojure.org/jira/browse/CLJ-2251
