### ISSUE TITLE
Data Spec does not have a name

### ISSUE THREAD

**Issue by furkan3ayraktar** [metosin/spec-tools#124]
`spec-tools.core/spec-name` returns `nil` for _data specs_. Since _data specs_ must have a name, it would be nice to be able to get that name from spec later on with `spec-name` function. For example:

```clojure
(ns data-spec-test.core
  (:require [spec-tools.core :as st]))

(def my-data
  (ds/spec {:name :model/my-data
            :spec {:id    common/uuid-string?
                   :name  string?
                   :age   pos-int?}}))

(st/spec-name my-data)
;; => nil
;; Expected value: :model/my-data

;; Currently I have to define specs like this, which is super redundant
(def my-data-2
  (assoc
    (ds/spec {:name :model/my-data-2
              :spec {:id    common/uuid-string?
                     :name  string?
                     :age   pos-int?}})
    :name :model/my-data-2))

(st/spec-name my-data-2)
;; => :model/my-data-2
```

**Comment by ikitommi** [comment]
`:name` is only mandatory for data-specs that emit `s/keys` specs, e.g. maps. So, this works:

```clj
(def my-data
  (ds/spec {:spec [[[[int?]]]]}))
```

my idea was that spec-tools would host a `local-keys` version of `s/keys` that didn't require keys to be registered, e.g. just values, `ds/spec` could optionally be pure after that.

still, setting the `:name` if it's given sound a good idea. Would you like to do a PR? Off to vacation for few weeks, hopefully somenone else would check and merge that.
