### ISSUE TITLE
Compound specs requirements are not reflected in Spec

### ISSUE THREAD

**Issue by shlomi-nx** [metosin/spec-tools#129]
Took me a long while to understand what the problem was:

Say I have this specs:
```clojure
(s/def :test/a string?)
(s/def :test/b string?)

(def t (st/spec (s/and (s/keys :req-un [:test/a])
                       (s/keys :req-un [:test/b]))))
```

the value of t is 
```clojure
{:spec
 #object[clojure.spec.alpha$and_spec_impl$reify__2173 0x662028dc "clojure.spec.alpha$and_spec_impl$reify__2173@662028dc"],
 :form
 (clojure.spec.alpha/and
  (clojure.spec.alpha/keys :req-un [:test/a])
  (clojure.spec.alpha/keys :req-un [:test/b])),
 :type :map,
 :keys #{:a},
 :keys/req #{:a}}
```

Which has only `:a` in its ':key' section. 

When this is plugged into compojure-api, the default transformer is removing "unneeded" keys, thus removing key `:b`, but then it immediately fails to conform, because `:b` is missing.

**Comment by miikka** [comment]
Hi! When combining `s/keys` specs in clojure.spec, my understanding is that you're meant to use [`s/merge`](https://clojure.github.io/spec.alpha/clojure.spec.alpha-api.html#clojure.spec.alpha/merge). This works with spec-tools:

```clojure
(s/def :test/a string?)
(s/def :test/b string?)

(def t (st/spec (s/merge (s/keys :req-un [:test/a])
                         (s/keys :req-un [:test/b]))))
```

```clojure
{:spec
 #object[clojure.spec.alpha$merge_spec_impl$reify__2186 0x58cdb828 "clojure.spec.alpha$merge_spec_impl$reify__2186@58cdb828"],
 :form
 (clojure.spec.alpha/merge
  (clojure.spec.alpha/keys :req-un [:test/a])
  (clojure.spec.alpha/keys :req-un [:test/b])),
 :type :map,
 :keys #{:b :a},
 :keys/req #{:b :a}}
```

Ideally this would work with `s/and` as well, although it does seem like a bit of a special case.

**Comment by ikitommi** [comment]
Have you tried the `st/merge`? Would it help with 2388? (proposed that long time ago, core team was not then interested). If that doesn't work, all ideas welcome how to fix this.

**Comment by ikitommi** [comment]
https://github.com/metosin/spec-tools/blob/master/test/cljc/spec_tools/core_test.cljc#L545-L594

**Comment by ikitommi** [comment]
`st/merge` should do it. Please reopen if it doesn't.
