### ISSUE TITLE
Parameters with specs loose the description

### ISSUE THREAD

**Issue by cjohansen** [metosin/spec-tools#135]
If you specify the description for a parameter, and then use `::swagger/parameters` to provide a spec for the same parameter, there is no way to include the description, as it is forcefully dropped by this line: https://github.com/metosin/spec-tools/blob/master/src/spec_tools/swagger/core.cljc#L98

I would expect the description to not be overwritten by an empty description.

**Comment by ikitommi** [comment]
It's a bug, would you like to make a PR?
