### ISSUE TITLE
Coercing issues

### ISSUE THREAD

**Issue by nenadalm** [metosin/spec-tools#145]
Hi. I am playing with `reitit` and since it started using `coerce` instead of `conform` my handler stopped working: https://github.com/nenadalm/spa-demo/blob/6ead886d34c263cc8c459f7ec8746f853c27c129/server/src/app/routes/user/handler.cljs#L44.

related change in `reitit`: https://github.com/metosin/reitit/commit/cb14cf017ab5175af8712f814b5279327341bb60#diff-b5391373d6c546daf15d41bb3a9368d2R125

I found that some assertion fails `Assert failed: missing spec predicate spec`. It fails in both clojure and clojurescript.

Here is code with which it can be reproduced:
```clj
(ns app.core
  (:require
   [clojure.spec.alpha :as s]
   [spec-tools.core :as st]))

(s/def :resource.user/id int?)
(s/def :resource/user (s/keys :req-un [:resource.user/id]))

(s/def :response.user/data :resource/user)
(s/def :response/user (s/keys :req-un [:response.user/data]))

(def no-op-transformer
  (reify
    st/Transformer
    (-name [_] ::no-op)
    (-encoder [_ _ _])
    (-decoder [_ _ _])))

(def spec (st/create-spec {:spec :response/user}))
(def value {:data {:id 41, :type "user", :attributes {:name "string"}}})
(def transformer no-op-transformer)

(comment
  ;; this works
  (st/conform spec value transformer)

  ;; Unhandled java.lang.AssertionError
  ;; Assert failed: missing spec predicate spec
  (st/coerce spec value transformer)
  )
```

project.clj
```clj
(defproject app "0.0.1-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [metosin/spec-tools "0.8.1"]
                 [org.clojure/clojurescript "1.10.439"]
                 [org.clojure/test.check "0.10.0-alpha2"]]
  :profiles {:dev
             {:dependencies [[com.bhauman/figwheel-main "0.1.9"]]}})
```

**Comment by ikitommi** [comment]
`[metosin/spec-tools "0.8.2"]` should have this fixed via https://github.com/metosin/spec-tools/commit/e6041cbcc88281900765c3798d67a29f56511964.

**Comment by ikitommi** [comment]
If this fixes the problem, I'll push out a new patch for reitit too.

**Comment by nenadalm** [comment]
thanks. that fixes the problem with reitit.
