### ISSUE TITLE
Support ClojureScript

### ISSUE THREAD

**Issue by miikka** [metosin/spec-tools#15]
`spec-tools.visitor` and `spec-tools.json-schema` should be made work as `.cljc` files. I quickly tried just renaming them, but tests didn't pass. Needs more investigation.

**Comment by miikka** [comment]
The problem with the visitor is that in CLJS, there's `clojure.core` instead of `cljs.core` and `cljs.spec` instead of `clojure.spec`. The problem with the JSON-Schema tests is that they use e.g. scjsv, which is Clojure-only.

**Comment by Deraen** [comment]
Should be quite easy to use any JS Json-Schema validator for Cljs tests instead of scjsv: http://json-schema.org/implementations

**Comment by miikka** [comment]
Yeah. I like [ajv](https://github.com/epoberezkin/ajv) the best, I've packaged it for cljsjs.

**Comment by miikka** [comment]
I was already worried that `s/form` may arbitrarily differ for cljs.spec and clojure.spec, but Alex Miller told me on Clojurians that they should be the same! That's good. I reported the `s/nilable` problem I discovered here: http://dev.clojure.org/jira/browse/CLJS-1890

---

For bonus points, we should also support self-hosted ClojureScript.

**Comment by miikka** [comment]
Works for now. I'll fix the nilable thing once CLJS-1890 is fixed. Supporting self-hosted CLJS would be nice, but there isn't much build tool support for it yet anyway, so I won't bother with it right now.
