### ISSUE TITLE
:reason doesn't compose as expected

### ISSUE THREAD

**Issue by mping** [metosin/spec-tools#171]
Please correct me if I'm wrong. I have the following:

```
(s/def ::k1 (st/spec {:spec string? :reason "k1"}))
(s/def ::k2 (st/spec {:spec string? :reason "k2"}))
(s/def ::spec (s/keys :req-un [::k1 ::k2]))
(s/def ::spec-with-reason {:reason "missingKey" :spec (s/keys :req-un [::k1 ::k2])})


(s/def ::spec (st/spec {:spec (s/keys :req-un [::k1 ::k2])}))
;; 1 - failed: k1 in: [:k1] at: [:k1] spec: :user/k1

(st/explain ::spec-with-reason {:k2 "2" :k1 1})
;; {:k2 "2", :k1 1} - failed: {:reason "missingKey", :spec (s/keys :req-un [:user/k1 :user/k2])} spec: :user/spec-with-reason
```
Shouldn't validation of `spec-with-reason` fail with `"k1"` instead?

**Comment by ikitommi** [comment]
I would expect that too.

**Comment by wandersoncferreira** [comment]
In the  `::spec-with-reason` example is missing a call to  `spec` again, no? The following works fine for me:

```clj
(s/def ::spec-with-reason (st/spec {:reason "missingKey" :spec (s/keys :req-un [::k1 ::k2])}))
(st/explain ::spec-with-reason {:k2 "2" :k1 1})

;; => 1 - failed: missingKey in: [:k1] at: [:k1] spec: :spec-tools.core/k1
```

Let me know if I am missing something here.

**Comment by Sardtok** [comment]
@wandersoncferreira The :reason is set to "missingKey", while it should be "k1". This is still the case with your fix to the spec, but the location of the error is correct here.

The wanted result is:
`1 - failed: k1 in: [:k1] at: [:k1] spec: :spec-tools.core/k1`
Not:
`1 - failed: missingKey in: [:k1] at: [:k1] spec: :spec-tools.core/k1`
