### ISSUE TITLE
Support generation of OpenApi 3.0 schemas 

### ISSUE THREAD

**Issue by asilverman** [metosin/spec-tools#192]
OpenAPI 3 has been around for a long time, it would be great if we could get v3 swagger schemas generated by spec-tools

**Comment by miikka** [comment]
A PR to implement this would be welcome. For guidance, you can take a look at [swagger/core.cljc](https://github.com/metosin/spec-tools/blob/master/src/spec_tools/swagger/core.cljc) which implements the Swagger/OpenAPI 2.0 schema generation and [json_schema.cljc](https://github.com/metosin/spec-tools/blob/master/src/spec_tools/json_schema.cljc) which implements the JSON Schema generation.

**Comment by miikka** [comment]
@asilverman, I just noticed that this issue is a duplicate of #105. I'm going to close this issue, but feel free to continue the discussion at #105.
