### ISSUE TITLE
Way to have instance of Spec record (with metadata) when explain

### ISSUE THREAD

**Issue by kirillsalykin** [metosin/spec-tools#24]
Hi,

Thanks a lot for this awesome lib!

Can you please help me, is this possible to have instance of Spec record when conform failed.

Consider this scenario.

```
(def my-integer? (st/spec ::st/long integer? {:error "not_integer"}))
(s/explain-data my-integer? "a")
```
I expect to have Spec instance to be able to indicate "not_integer" to user.

Maybe there is spect-tools/explain?

Please advice how I can solve this, thanks!

**Comment by ikitommi** [comment]
Sounds like a good idea. At some point, the spec keys should be namespaced to avoid collisions. Will try to cut out a non-snapshot soon, with ~this in it.

**Comment by ikitommi** [comment]
Fixed a lot of stuff: a better syntax for the `st/spec`, type-hint as `:spec/type`, automatic type resolution for core predicates, all core predicates predefined as Specs etc. There is also now a `:spec/reason`, which get's merged into the problems to be extracted via `s/explain` or `s/explain-data`. We will try to freeze things this week for 0.1.0.

Feedback welcome.

```clj
(s/explain (st/spec pos-int? {:spec/reason "positive"}) -1)
; val: -1 fails predicate: pos-int?,  positive

(s/explain-data (st/spec pos-int? {:spec/reason "positive"}) -1)
; #:clojure.spec{:problems [{:path [], :pred pos-int?, :val -1, :via [], :in [], :reason "positive"}]}
```
