### ISSUE TITLE
Link to Spec Transformers post returns 404

### ISSUE THREAD

**Issue by werenall** [metosin/spec-tools#280]
https://github.com/metosin/spec-tools/blob/7a3b59e9d3ed2849c89c8a0b10d5a57198e84027/README.md?plain=1#L20

Is there a chance this post is still available somewhere? If not, I could create a simple PR removing this line.

**Comment by ikitommi** [comment]
I think this is the correct url: https://www.metosin.fi/blog/2018-05-14-spec-transformers

**Comment by Deraen** [comment]
Post returned to the old URL
