### ISSUE TITLE
better s/merge for JSON Schema

### ISSUE THREAD

**Issue by ikitommi** [metosin/spec-tools#48]
```clj
(require '[clojure.spec :as s])

(s/def :int/a int?)
(s/def :string/a string?)
(s/def ::merge
  (s/merge
    (s/keys :req-un [:int/a])
    (s/keys :req-un [:string/a])))

(s/explain ::merge {:a 1})
; In: [:a] val: 1 fails spec: :string/a at: [:a] predicate: string?

(s/explain ::merge {:a "1"})
; In: [:a] val: "1" fails spec: :int/a at: [:a] predicate: int?
```

=> for JSON Schema, should emit `:allOf` from this?

**Comment by miikka** [comment]
I think `:allOf` would match the `s/merge` semantics.

That said, this example is a bit silly in the sense that there are no values that would conform to `::merge`. Here's another example that is at least satisfied by some values.

```clj
(s/def :neutral/int int?)
(s/def :positive/int pos?)
(s/def ::merge (s/merge (s/keys :req-un [:neutral/int]) (s/keys :req-un [:positive/int])))
```

I'd be interested to see a real-world use case for this.

**Comment by ikitommi** [comment]
agree, this is a dusty corner case, but now at least it's documented :)

**Comment by ikitommi** [comment]
maybe later.
