### ISSUE TITLE
Possible improvement to data-spec/spec

### ISSUE THREAD

**Issue by Severed-Infinity** [metosin/spec-tools#66]
Working with the `data-spec/spec` function I find myself repeating myself a lot to achieve functionality in a spec manner, by that in how I need things to feel like I am still working with spec itself.

I love the functionality of it but due to my approach, I find I'm not using it optimally and could pretty much stick to just Clojure spec by itself to achieve my goals. Anyway enough of my crazyish rant and to explain with a bit of code.

Using some fake code as an example following your guidelines as follows, I'm not sure about the second map with `:description` and `:reason` if I am using right or even using it in the right context.
```
(def fake-tag
  (st-ds/spec
    ::fake-tag
    {:tag (s/and keyword? #{:fake-tag})}
    {:description "fake tag"
     :reason "doesn't match format"}))

(st-c/conform fake-tag :fake-tag)
```

As you can see I create the spec then check if it conforms but what I am finding myself doing a lot is the following, in fact all the time, when using `data-spec/spec` is the following.

```
(s/def ::fake-tag
  (st-ds/spec
    ::fake-tag
    {:tag (s/and keyword? #{:fake-tag})}
    {:description "fake tag"
     :reason "doesn't match format"}))

(st-c/conform ::fake-tag :fake-tag)
```
As you can see I duplicate the namespaced key and using `spec/def` to register the spec in a more consistent spec manner just so I can use `conform` and the other related functions with a namespace key.

So what I am trying to say is I'd like to see `data-spec/spec` changed slight if possible to like the following, again if possible. Make the `data-spec/spec` registration be top level like the Clojure spec `s/def` to reduce the need for extra binding.
```
(st-ds/spec
  ::fake-tag
  {:tag (s/and keyword? #{:fake-tag})}
  {:description "fake tag"
   :reason "doesn't match format"}))

(st-c/conform ::fake-tag :fake-tag)
```

Sorry for my ramble at the beginning but hope it helps convey what I mean.

**Comment by Severed-Infinity** [comment]
I feel like it is slightly relatable to this issue https://github.com/metosin/spec-tools/issues/55 in that using the approach I take already 
```
(s/def ::fake-tag
  (st-ds/spec
    ::fake-tag
    {:tag (s/and keyword? #{:fake-tag})}
    {:description "fake tag"
     :reason "doesn't match format"}))
```
could inform the name of the spec in the "anonymous" approach 
```
(s/def ::fake-tag
  (st-ds/spec
    {:tag (s/and keyword? #{:fake-tag})}
    {:description "fake tag"
     :reason "doesn't match format"}))

==> equilivant to each other

(s/def ::fake-tag
  (st-ds/spec
    ::fake-tag
    {:tag (s/and keyword? #{:fake-tag})}
    {:description "fake tag"
     :reason "doesn't match format"}))
```

**Comment by miikka** [comment]
I haven't thought this through yet, but here are my initial thoughts: I'm quite sure we don't want to change `spec-tools.data-spec/spec` to register the definitions – like `clojure.spec.alpha/spec`, it's going to just return the spec – but maybe it'd make sense to have `spec-tools.data-spec/def` that would work like what you suggest.

```clojure
(st-ds/def
  ::fake-tag
  {:tag (s/and keyword? #{:fake-tag})}
  {:description "fake tag"
    :reason "doesn't match format"}))

;; ==> expand to

(s/def ::fake-tag
  (st-ds/spec
    ::fake-tag
    {:tag (s/and keyword? #{:fake-tag})}
    {:description "fake tag"
     :reason "doesn't match format"}))
```

**Comment by Severed-Infinity** [comment]
Yea I think looks like it would be best of both worlds.
Just in regards to the map used above
```
{:description "fake tag"
  :reason "doesn't match format"}
```
I am taking it from the readme file with the table of map arguments that can be passed to `spec-tools.core/create-spec`, am I using it correctly in the above examples, at least from reading through the source on `spec-tools.data-spec/spec` it takes a third optional argument that I assume relates to this but from testing in the REPL this does not seem to be when using `conform` and `explain-data` to get an intentional error output.

**Comment by ikitommi** [comment]
For now, you can create the custom `def` macro on you client project. `ds/spec` doesn't currently take the extra meta as a third argument, but I think it should..

**Comment by ikitommi** [comment]
closing this
