### ISSUE TITLE
Type resolution of s/and forms

### ISSUE THREAD

**Issue by cddr** [metosin/spec-tools#68]
Currently, it seems like specs involving `s/and` do not have their type auto-resolved (or rather they auto-resolve to `nil`). What do you think about defaulting to resolve to the type of the first mentioned predicate. This seems to be how the underlying generators work. Maybe this wouldn't be the right thing in all situations but seems like a decent default.

https://clojure.org/guides/spec#_using_code_s_and_code_generators

**Comment by miikka** [comment]
Makes sense to me. Spec docs espouse this pattern and it'd provide better guesses than `nil`. 

(FYI: both me and Tommi are on vacation so we might respond to the issues and PRs quite slowly until mid-August.)

**Comment by ikitommi** [comment]
Thanks! Pushed quickly out into `[metosin/spec-tools "0.3.1-20170722.080756-1"]´.
