### ISSUE TITLE
Failing on extra keys

### ISSUE THREAD

**Issue by bbss** [metosin/spec-tools#76]
I have interest in checking my data-structures for erroneous keys (any key that is not in the spec in this case.) I thought that spec-tools 'fail-on-extra-keys` seems perfect for exactly that. 

But I can't figure out how to use it. Is this a bug?

```clojure
(require '[spec-tools.core :as spec-tools])
(spec/def ::attr #{"value"})
(spec/def ::has-key (spec/keys opt [::attr]))

(spec-tool/conform
 ::has-key
 #:noextrakey.clj.core
 {:attr "value"
  :other-attr "still-valid?"}
 spec-tool/fail-on-extra-keys-conforming)
```

**Comment by ikitommi** [comment]
Hi. You need to wrap Specs into Spec Records as `clojure.spec` doesn't support runtime conforming and core Specs can't be extended. There is a [Issue](https://dev.clojure.org/jira/browse/CLJ-2116) describing why and a patch to fix it. Go vote it up.

> I don't think we are interested in turning spec into a transformation engine via conformers, so I suspect we are probably not interested. However, I'll leave it for Rich to assess.

Before / if ever that is resolved, instead of:

```clj
(require '[spec-tools.core :as st])
(require '[clojure.spec.alpha :as s])

(s/def ::attr #{"value"})
(s/def ::has-key (s/keys :opt [::attr]))

(st/conform
  ::has-key
  #:noextrakey.clj.core
      {:attr "value"
       :other-attr "still-valid?"}
  spec-tool/fail-on-extra-keys-conforming)
; #:noextrakey.clj.core{:attr "value", :other-attr "still-valid?"}
```

you need to:

```
(require '[spec-tools.core :as st])
(require '[clojure.spec.alpha :as s])

(s/def ::attr #{"value"})
(s/def ::has-key (st/spec (s/keys :opt [::attr])))

(st/explain
  ::has-key
  #:noextrakey.clj.core
      {:attr "value"
       :other-attr "still-valid?"}
  spec-tool/fail-on-extra-keys-conforming)
```

**Comment by bbss** [comment]
Alright, that's clear. Thanks!
