### ISSUE TITLE
ds/opt vs ds/maybe

### ISSUE THREAD

**Issue by Atsman** [metosin/spec-tools#77]
Hello, i find it difficult to understand when should i use ds/opt vs when to use ds/maybe?

Could someone explain that, may it should be documented?

**Comment by ikitommi** [comment]
Hi. `ds/opt` effects the key (can be left out) while the `ds/maybe` effects the value (can be `nil`). A key the be left out and the value can be nil requires both:

```clj
{(ds/opt :user) (ds/maybe {:name string?})}
```

Better docs are welcome (via PRs).

**Comment by Atsman** [comment]
Hi, i got it. ds/opt accepts that map do not have the key. ds/maybe will not accept absence of key, but will accept the value nil. Thank you for explanation!
