### ISSUE TITLE
Class cast exception when attempting to coerce spec

### ISSUE THREAD

**Issue by mgrbyte** [metosin/spec-tools#79]
I have a spec which is giving the error:
`java.lang.ClassCastException: clojure.lang.PersistentList cannot be cast to clojure.lang.Named`
when attempting to load the swagger UI for a compojure-api app.
The [failing spec][1] appears to be one that uses conditional keys in a `:req` parameter of a `clojure.spec/keys` declaration.

Environment:
 * `[org.clojure/clojure "1.9.0-alpha17"]`
 * `[metosin//compojure-api "2.0.0-alpha7"]`
 * `[metosin/spec-tools "0.4.0-SNAPSHOT"]`

[1]: https://github.com/mgrbyte/wormbase-names/blob/feature/create-names/src/org/wormbase/specs/gene.clj#L105-L111

**Comment by mgrbyte** [comment]
A full copy of the traceback:
[spec-class-cast-tb.txt](https://github.com/metosin/spec-tools/files/1362973/spec-class-cast-tb.txt)

**Comment by ikitommi** [comment]
Problem was that the `or` and `and` were not parsed correctly under `s/keys` required keys. Should be fixed now, could you verify with `[metosin/spec-tools "spec-tools-0.4.0-20171007.191128-3"]`.

**Comment by mgrbyte** [comment]
@ikitommi I can verify that `0.4.0-20171007.191128-3` fixes the issue. Thanks for looking into it so quickly! :+1: :100:
