### ISSUE TITLE
Support multi-spec parsing

### ISSUE THREAD

**Issue by ikitommi** [metosin/spec-tools#84]
see https://github.com/jpmonettas/inspectable/blob/master/src/inspectable/spec_utils.cljc#L24

**Comment by talgiat** [comment]
So multi-spec is not supported for coercion?

**Comment by ikitommi** [comment]
Might work with dynamic conforming, but not with plain coercion. PR welcome for this!

**Comment by Astronought** [comment]
Any update on this? Would be very nice to have :)

**Comment by ikitommi** [comment]
Not working on this. Any help welcome.
