### ISSUE TITLE
Compatibilty with Clojure 1.9.0-beta4 regarding the suppression of bigdec?

### ISSUE THREAD

**Issue by hiram-madelaine** [metosin/spec-tools#85]
In  Clojure 1.9.0-beta4, the new predicate introduced in 1.9 is finally remove.
As spec-tools uses this predicate it is not compatible with this beta.

**Comment by ikitommi** [comment]
Thanks. Did a quick PR for this.

**Comment by ikitommi** [comment]
`[metosin/spec-tools "0.5.1"]`
