### ISSUE TITLE
Validation by comparing keys.

### ISSUE THREAD

**Issue by AlexTheLost** [metosin/spec-tools#87]
Hello, my problem is - need compare two values from Map for validate. For example that value of one key less than value of another key.
`{ :floor 5 :total-floor 10 } `- For flat on 5 floor in building with 10 floors.
Can achieves this with spec-tools and clojure.spec?

**Comment by ikitommi** [comment]
Hi.

You can do that with just `clojure.spec`:

```clj
(require '[clojure.spec.alpha :as s])

(s/def ::floor int?)
(s/def ::total-floor int?)

(s/def ::map 
  (s/and (s/keys :req-un [::floor ::total-floor]) 
         #(< (:floor %) (:total-floor %))))

(s/valid? ::map {:floor 10, :total-floor 20})
; true

(s/valid? ::map {:floor 40, :total-floor 20})
; false
```

cheers,

Tommi

**Comment by AlexTheLost** [comment]
Thank you very much.

**Comment by AlexTheLost** [comment]
Thank you very much.
