### ISSUE TITLE
Gracefully show errors even if not all referenced specs are defined

### ISSUE THREAD

**Issue by slipset** [metosin/spec-tools#89]
Given an api with spec-conversion which uses a spec like
```
(s/def ::foo (s/keys :req-un [::bar]))
```
where bar `::bar` is undefined, makes swagger show
```
500 : {"type":"unknown-exception","class":"java.lang.Exception"} http://localhost:3000/swagger.json
```
It would be nice if it would still show the other api -endpoints and maybe inform me of the offending spec.

**Comment by ikitommi** [comment]
Fixed by https://github.com/metosin/compojure-api/pull/358
