### ISSUE TITLE
Map keys not conformed

### ISSUE THREAD

**Issue by bartfrenk** [metosin/spec-tools#97]
In

```clojure
[metosin/spec-tools "0.5.1"]
```
doing this

```clojure
(s/def ::int-map (st/spec (s/map-of spec/int? spec/int?)))
(st/conform ::int-map {"1" "2"} st/string-conforming)
```
results in
```
{"1" 2}
```
which, if not a bug, is suprising behaviour to me.

**Comment by ikitommi** [comment]
Hi. It's a feature of  `clojure.spec`. By default, the keys of `map-of` are not conformed, see [the docs](https://clojuredocs.org/clojure.spec/map-of).

This works:

```clj
(s/def ::int-map (st/spec (s/map-of spec/int? spec/int? :conform-keys true)))
(st/conform ::int-map {"1" "2"} st/string-conforming)
; {1 2}
```

Agree it's surprising.

**Comment by bartfrenk** [comment]
Oops. Thanks!
